"use client";

/**
 * v168 — Tools picker shown above the TOOLS.md textarea in both the
 * agent create wizard and the agent editor (AgentBrainPanel).
 * v171 — picker is now LIVE: when a `companyId` is provided it fetches
 *         /api/Agents/tools-catalog/{companyId} and renders cards with
 *         the actual config (daily/per-call Apify caps, real
 *         endpoint URLs, "wired"/"not configured" states). The
 *         template generated by "Insert template" is also dynamic —
 *         only mentions tools the company has actually wired.
 *
 * Recipes covered:
 *   • Notes Vault (Obsidian-compatible) — always wired when gateway
 *     hooks are configured
 *   • Email drafts via the Notes Vault (uses the same endpoint, but
 *     conventions live under emails/* — operator dispatches via the
 *     Lead inbox)
 *   • Instagram scraper (Apify) — needs per-company Apify token
 *   • Apify generic — same wiring as Instagram, different actors
 *
 * The cards are NOT toggleable — they reflect what the runtime would
 * inject right now. To turn one off, configure it off (e.g. clear
 * the Apify token in User → Tools).
 */

import { useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  BookOpen,
  Camera,
  ChevronDown,
  ChevronUp,
  Loader2,
  Mail,
  Network,
  Sparkles,
  Wand2,
} from "lucide-react";
import { AGENT_TOOLS_TEMPLATE } from "@/lib/agents/agentFiles";
import {
  fetchAgentToolsCatalog,
  type AgentToolsCatalog,
} from "@/lib/agents/backend-api";

type RecipeId = "notes-vault" | "email-drafts" | "instagram-apify" | "apify-generic";

type RecipeMeta = {
  id: RecipeId;
  icon: typeof BookOpen;
  title: string;
  oneLiner: string;
  description: string;
  defaultEndpoint: string;
};

const RECIPE_META: Record<RecipeId, RecipeMeta> = {
  "notes-vault": {
    id: "notes-vault",
    icon: BookOpen,
    title: "Notes Vault (Obsidian-compatible)",
    oneLiner: "Persistent markdown notes on S3 — same vault the operator opens in Obsidian.",
    description:
      "Lets the agent write durable notes the operator (and other agents) can read. Path conventions: briefings/, leads/, playbooks/, journal/. Idempotent: same path overwrites.",
    defaultEndpoint: "POST /api/CompanyNotes/agent/{companyId}/note  (X-Bridge-Token)",
  },
  "email-drafts": {
    id: "email-drafts",
    icon: Mail,
    title: "Email drafts (via Notes Vault)",
    oneLiner: "Agent prepares email drafts in the vault; operator reviews + dispatches via Lead inbox.",
    description:
      "Drafts live under emails/outbound/ (one-offs), emails/sequences/ (templates), or emails/replies/ (proposed responses). Front-matter holds to/subject/replyTo/status; body is plain markdown.",
    defaultEndpoint: "POST /api/CompanyNotes/agent/{companyId}/note  (path: emails/...)",
  },
  "instagram-apify": {
    id: "instagram-apify",
    icon: Camera,
    title: "Instagram scraper (Apify)",
    oneLiner: "Third-party Instagram reads via Apify when Meta Graph can't reach.",
    description:
      "POST handles[] / hashtags[] / directUrls[]. Daily and per-call caps enforced; results persist to scrapes/instagram/ in the vault by default.",
    defaultEndpoint: "POST /api/InstagramScrape/agent/{companyId}/run  (X-Bridge-Token)",
  },
  "apify-generic": {
    id: "apify-generic",
    icon: Network,
    title: "Apify generic actor",
    oneLiner: "Same endpoint, route by actor — Twitter, LinkedIn, web crawlers, etc.",
    description:
      "Reuses the Instagram bridge endpoint with a different `actor` field. Costs the same daily Apify budget — always summarize first and ask before pulling more.",
    defaultEndpoint: "POST /api/InstagramScrape/agent/{companyId}/run  (actor:<name>)",
  },
};

type ResolvedRecipe = RecipeMeta & {
  configured: boolean;
  endpoint: string;
  perCallCap?: number | null;
  dailyCap?: number | null;
  reason?: string | null;
};

const MARKER_START = "<!-- okestria:auto-tools:start -->";
const MARKER_END = "<!-- okestria:auto-tools:end -->";

/** Strip any v84 managed section from previously-loaded TOOLS content
 *  so the operator's textarea only ever shows their authored block. */
export function stripAutoToolsSection(content: string): string {
  if (!content) return "";
  const startIdx = content.indexOf(MARKER_START);
  if (startIdx < 0) return content;
  const endIdx = content.indexOf(MARKER_END, startIdx);
  if (endIdx < 0) {
    return content.slice(0, startIdx).trimEnd();
  }
  const before = content.slice(0, startIdx).trimEnd();
  const after = content.slice(endIdx + MARKER_END.length).trimStart();
  if (!after) return before;
  return `${before}\n\n${after}`;
}

function resolveRecipesFromCatalog(catalog: AgentToolsCatalog | null): ResolvedRecipe[] {
  // Without a catalog we still render every recipe but tagged
  // "configuration unknown" — better than hiding everything.
  if (!catalog) {
    return (Object.keys(RECIPE_META) as RecipeId[]).map((id) => ({
      ...RECIPE_META[id],
      configured: true,
      endpoint: RECIPE_META[id].defaultEndpoint,
      reason: null,
    }));
  }
  return [
    {
      ...RECIPE_META["notes-vault"],
      configured: catalog.notesVault.configured,
      endpoint: catalog.notesVault.endpoint ?? RECIPE_META["notes-vault"].defaultEndpoint,
      reason: catalog.notesVault.note ?? null,
    },
    {
      ...RECIPE_META["email-drafts"],
      configured: catalog.email.configured,
      endpoint: catalog.email.endpoint ?? RECIPE_META["email-drafts"].defaultEndpoint,
      reason: catalog.email.note ?? null,
    },
    {
      ...RECIPE_META["instagram-apify"],
      configured: catalog.instagramApify.configured,
      endpoint: catalog.instagramApify.endpoint ?? RECIPE_META["instagram-apify"].defaultEndpoint,
      perCallCap: catalog.instagramApify.perCallCap ?? null,
      dailyCap: catalog.instagramApify.dailyCap ?? null,
      reason: catalog.instagramApify.note ?? null,
    },
    {
      ...RECIPE_META["apify-generic"],
      configured: catalog.apifyGeneric.configured,
      endpoint: catalog.apifyGeneric.endpoint ?? RECIPE_META["apify-generic"].defaultEndpoint,
      perCallCap: catalog.apifyGeneric.perCallCap ?? null,
      dailyCap: catalog.apifyGeneric.dailyCap ?? null,
      reason: catalog.apifyGeneric.note ?? null,
    },
  ];
}

/**
 * v171 — Build a starter operator-authored TOOLS template that ONLY
 * mentions the tools this company actually has wired. Falls back to
 * the static template if no catalog is available.
 */
function buildDynamicTemplate(recipes: ResolvedRecipe[]): string {
  const wired = recipes.filter((r) => r.configured);
  if (wired.length === 0) return AGENT_TOOLS_TEMPLATE;

  const lines: string[] = [];
  lines.push("# TOOLS — operator notes");
  lines.push("");
  lines.push("How I use my available tools, and the conventions I follow.");
  lines.push("");
  lines.push("## Default behaviors");
  lines.push("");
  lines.push("- Always confirm destructive actions with the operator before running them.");
  lines.push("- Prefer reading existing notes (Notes Vault) before scraping fresh data.");
  lines.push("- When a third-party scrape costs API budget, summarize first, then ask before pulling more.");
  lines.push("");

  const has = (id: RecipeId) => wired.some((r) => r.id === id);

  if (has("notes-vault")) {
    lines.push("## Notes Vault — when I write");
    lines.push("");
    lines.push("- Daily briefings: `briefings/YYYY-MM-DD-<topic>.md`");
    lines.push("- Lead summaries: `leads/<handle>.md`");
    lines.push("- Playbooks: `playbooks/<topic>.md`");
    lines.push("- Journal: `journal/YYYY-MM-DD.md`");
    lines.push("");
  }
  if (has("email-drafts")) {
    lines.push("## Email — drafts only (operator dispatches)");
    lines.push("");
    lines.push("- One-offs: `emails/outbound/<recipient>-YYYY-MM-DD-<slug>.md`");
    lines.push("- Sequence steps: `emails/sequences/<sequence>/<step>.md`");
    lines.push("- Reply drafts: `emails/replies/<thread-id>.md`");
    lines.push("- Always include front-matter: `to`, `subject`, optional `replyTo`, and `status: draft`.");
    lines.push("- Mention the path in my reply so the operator can find it.");
    lines.push("");
  }
  if (has("instagram-apify")) {
    const ig = wired.find((r) => r.id === "instagram-apify");
    const cap = ig?.perCallCap ?? 12;
    lines.push("## Instagram scraping — what I capture");
    lines.push("");
    lines.push(`- Default \`resultsType: "posts"\`, \`limit: ${Math.min(12, cap)}\` unless the operator says otherwise.`);
    lines.push("- Always set `persistToVault: true` so the run is replayable later.");
    lines.push("- If the daily Apify budget is exhausted, STOP and tell the operator in the reply.");
    lines.push("");
  }
  if (has("apify-generic")) {
    lines.push("## Apify (other actors)");
    lines.push("");
    lines.push("- Same `/api/InstagramScrape/agent/{companyId}/run` endpoint, different `actor` field.");
    lines.push("- Confirm with the operator before invoking — every call costs the daily budget.");
    lines.push("");
  }

  lines.push("## Custom shortcuts");
  lines.push("");
  lines.push("(Add team-specific tool shortcuts here — slash-commands, sheet templates, etc.)");
  lines.push("");
  return lines.join("\n");
}

export function AgentToolsPicker({
  value,
  onChange,
  companyId,
}: {
  value: string;
  onChange: (next: string) => void;
  /** Optional — when provided, the picker fetches the live tools
   *  catalog for this company to show real config in cards and to
   *  generate a dynamic operator template. */
  companyId?: number | null;
}) {
  const [previewOpen, setPreviewOpen] = useState(false);
  const [catalog, setCatalog] = useState<AgentToolsCatalog | null>(null);
  const [catalogLoading, setCatalogLoading] = useState<boolean>(Boolean(companyId));

  useEffect(() => {
    if (!companyId) {
      setCatalogLoading(false);
      return;
    }
    let cancelled = false;
    setCatalogLoading(true);
    void fetchAgentToolsCatalog({ companyId }).then((result) => {
      if (cancelled) return;
      setCatalog(result);
      setCatalogLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, [companyId]);

  const recipes = useMemo(() => resolveRecipesFromCatalog(catalog), [catalog]);
  const wiredRecipes = useMemo(() => recipes.filter((r) => r.configured), [recipes]);
  const dynamicTemplate = useMemo(() => buildDynamicTemplate(recipes), [recipes]);

  const handleInsertTemplate = () => {
    const next = dynamicTemplate;
    if (!value.trim()) {
      onChange(next);
      return;
    }
    const ok =
      typeof window !== "undefined"
        ? window.confirm(
            "Replace the current TOOLS notes with the starter template? Your existing content will be lost.",
          )
        : true;
    if (ok) onChange(next);
  };

  const composedPreview = buildComposedPreview(value, wiredRecipes);

  return (
    <div className="space-y-4">
      {/* Heading + insert-template button */}
      <div className="flex items-start justify-between gap-3 rounded-2xl border border-cyan-400/25 bg-gradient-to-br from-cyan-500/[0.08] to-violet-500/[0.05] px-4 py-3">
        <div className="min-w-0">
          <p className="font-mono text-[10.5px] uppercase tracking-[0.22em] text-cyan-200/80">
            Tools available to this agent
          </p>
          <p className="mt-1 text-[12.5px] leading-relaxed text-white/75">
            The runtime composer auto-injects the recipes below into{" "}
            <span className="font-mono text-cyan-200/85">TOOLS.md</span> at session start.
            Anything you type in the textarea further down is preserved as the operator
            block above the auto-injected section.
          </p>
          {catalogLoading ? (
            <p className="mt-1 inline-flex items-center gap-1.5 text-[11px] text-white/50">
              <Loader2 className="h-3 w-3 animate-spin" />
              Reading the live tools catalog for this company…
            </p>
          ) : catalog ? (
            <p className="mt-1 text-[11px] text-emerald-300/80">
              Live catalog · {wiredRecipes.length} of {recipes.length} tools wired.
            </p>
          ) : null}
        </div>
        <button
          type="button"
          onClick={handleInsertTemplate}
          disabled={catalogLoading}
          className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-cyan-400/45 bg-cyan-500/15 px-3 py-1.5 text-[11.5px] font-semibold text-cyan-100 transition hover:bg-cyan-500/25 disabled:opacity-40"
        >
          <Wand2 className="h-3.5 w-3.5" />
          {value.trim() ? "Replace with template" : "Insert template"}
        </button>
      </div>

      {/* v173 — slim cards: icon + name + wired chip + (optional caps).
         Operator wanted a clean tool list, not a recipe textbook —
         the long descriptions/endpoints/reasons live in the Composed
         Preview details below for anyone who needs them. The hover
         tooltip surfaces the one-liner / "why off" reason. */}
      <div className="grid gap-2 sm:grid-cols-2">
        {recipes.map((recipe) => {
          const Icon = recipe.icon;
          const showCaps =
            recipe.configured &&
            (typeof recipe.perCallCap === "number" || typeof recipe.dailyCap === "number");
          return (
            <div
              key={recipe.id}
              title={recipe.configured ? recipe.oneLiner : recipe.reason ?? recipe.oneLiner}
              className={`flex items-center gap-2.5 rounded-xl border px-3 py-2 ${
                recipe.configured
                  ? "border-white/10 bg-white/[0.02]"
                  : "border-white/5 bg-white/[0.01] opacity-60"
              }`}
            >
              <span
                className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border ${
                  recipe.configured
                    ? "border-cyan-400/30 bg-cyan-500/10 text-cyan-300"
                    : "border-white/10 bg-white/[0.03] text-white/35"
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
              </span>
              <span className="min-w-0 flex-1 truncate text-[12.5px] font-medium text-white">
                {recipe.title}
              </span>
              {showCaps ? (
                <span className="shrink-0 rounded-md border border-white/10 bg-white/[0.04] px-1.5 py-0.5 font-mono text-[9px] text-white/55">
                  {recipe.perCallCap ?? "?"}/{recipe.dailyCap ?? "?"}
                </span>
              ) : null}
              {recipe.configured ? (
                <span className="shrink-0 rounded-md border border-emerald-400/30 bg-emerald-500/10 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.18em] text-emerald-200">
                  wired
                </span>
              ) : (
                <span className="shrink-0 rounded-md border border-amber-400/30 bg-amber-500/10 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.18em] text-amber-200">
                  off
                </span>
              )}
            </div>
          );
        })}
      </div>

      {/* If nothing wired, gentle warning */}
      {wiredRecipes.length === 0 && !catalogLoading ? (
        <div className="flex items-start gap-2 rounded-xl border border-amber-400/30 bg-amber-500/[0.06] px-3 py-2 text-[12px] text-amber-100/85">
          <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <span>
            No auto-inject recipes are wired for this company. The agent will only see the
            operator-authored TOOLS notes below. Configure them in Admin → Gateway and User → Tools.
          </span>
        </div>
      ) : null}

      {/* Composed preview */}
      <details
        open={previewOpen}
        onToggle={(e) => setPreviewOpen((e.target as HTMLDetailsElement).open)}
        className="rounded-xl border border-white/10 bg-black/30"
      >
        <summary className="flex cursor-pointer items-center justify-between gap-2 px-4 py-2.5 transition hover:bg-white/[0.03]">
          <span className="inline-flex items-center gap-2 font-mono text-[10.5px] uppercase tracking-[0.22em] text-white/55">
            <Sparkles className="h-3.5 w-3.5 text-cyan-300/70" />
            Composed TOOLS.md preview ({composedPreview.length} chars)
          </span>
          {previewOpen ? (
            <ChevronUp className="h-3.5 w-3.5 text-white/55" />
          ) : (
            <ChevronDown className="h-3.5 w-3.5 text-white/55" />
          )}
        </summary>
        <pre className="m-3 mt-0 max-h-72 overflow-auto rounded-lg border border-white/8 bg-black/40 p-3 font-mono text-[11px] leading-relaxed text-cyan-100/85">
          {composedPreview}
        </pre>
      </details>
    </div>
  );
}

/**
 * v168 — Browser-side composed preview that mirrors what the back's
 * AgentRecipeComposer.ComposeToolsFile produces. Strict text parity
 * isn't required (the actual recipe text is generated server-side
 * with the company's hookBaseUrl + token), so we render a compact
 * placeholder for each recipe block instead.
 */
function buildComposedPreview(operatorContent: string, recipes: ResolvedRecipe[]): string {
  const op = stripAutoToolsSection(operatorContent ?? "").trim();
  if (recipes.length === 0) return op;

  const lines: string[] = [];
  if (op) {
    lines.push(op);
    lines.push("");
    lines.push("");
  }
  lines.push(MARKER_START);
  lines.push("<!--");
  lines.push("  Auto-injected by Okestria so the chat agent has the same recipes");
  lines.push("  cron + squad get at dispatch time. Edit your operator-authored");
  lines.push("  TOOLS notes ABOVE this marker — anything between the markers is");
  lines.push("  rewritten on every profile sync.");
  lines.push("-->");
  for (const recipe of recipes) {
    lines.push("");
    lines.push(`## ${recipe.title.toUpperCase()}`);
    lines.push("");
    lines.push(recipe.oneLiner);
    lines.push("");
    lines.push("Endpoint (filled in at runtime with your hookBaseUrl + token):");
    lines.push("```");
    lines.push(recipe.endpoint);
    lines.push("```");
    lines.push("");
  }
  lines.push("");
  lines.push(MARKER_END);
  return lines.join("\n");
}
